version: "3.9"
services:
  api:
    build: ./api
    container_name: expressapp_c
    ports:
      - "8000:4000"
    volumes:
      - ./api:/app
      
  myblog:
    build: ./myblog
    container_name: blogreactapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    stdin_open: true
    tty: true